version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: MIX_ENV=test mix coveralls.json
      - run: mix format --check-formatted
      - run: mix dialyzer
      - run: bash <(curl -s https://codecov.io/bash)
